---
- name: Export ASM policies
  hosts: all
  connection: local
  vars:
    provider:
      password: <password>
      server: <IP address>
      user: <user>
      validate_certs: no
      server_port: <port>	
  tasks:
  - name: Collect ASM policies
    bigip_device_info:
      gather_subset:
        - asm-policies 
      provider: "{{provider}}"
    delegate_to: localhost
    register: device_policies
  
  - name: Export compact policy in XML format
    bigip_asm_policy_fetch:
      name: "{{ item.name }}"
      file: "{{ item.name }}.xml"
      dest: <path>
      compact: true
      provider: "{{ provider }}"
    loop: "{{ device_policies | community.general.json_query('asm_policies') }}"
    loop_control:
      label: "{{ item.name }}"
