---
- name: Import ASM policies
  hosts: all
  connection: local
  vars:
    provider:
      password: admin
      server: 10.155.132.173
      user: admin
      validate_certs: no
      server_port: 443	
  tasks:
  - name: Get policy names from directory 
    find:
      paths: "/Users/adamski.molina/Documents/ansible_case/policies"
    register: policy_names

  - name: print file names without path
    debug:
      msg: "{{ policy_names['files'] | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"
  
  - name: Import ASM Policies 
    bigip_asm_policy_import:
      name: "{{ item }}"
      source: "/Users/adamski.molina/Documents/ansible_case/policies/{{ item }}"
      provider: "{{ provider }}"
    loop: "{{ policy_names['files'] | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"
    loop_control:
      label: "{{ item }}"
 
