---
- name: Import ASM policies
  hosts: all
  connection: local
  vars:
    provider:
      password: <password>
      server: <IP address>
      user: <user>
      validate_certs: no
      server_port: <port>	
  tasks:
  - name: Get policy names from the directory 
    find:
      paths: <path>
    register: policy_names

  - name: print file names without path
    debug:
      msg: "{{ policy_names['files'] | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"
  
  - name: Import ASM Policies 
    bigip_asm_policy_import:
      name: "{{ item }}"
      source: "<path>{{ item }}"
      provider: "{{ provider }}"
    loop: "{{ policy_names['files'] | map(attribute='path') | map('regex_replace','^.*/(.*)$','\\1') | list }}"
    loop_control:
      label: "{{ item }}"
 
